### ISSUE TITLE
Feature request: Allow toggle for "No shadows on vertically maximized windows"

### ISSUE THREAD

**Issue by BLuFeNiX** [nathan818fr/cinnamon-user-shadows#2]
I would like to only have no shadows when a window is vertically maximized. For example, we can set this flag via wmctrl:

```
wmctrl -r :ACTIVE: -b add,maximized_vert
```

**Comment by nathan818fr** [comment]
Unfortunately, the cinnamon window manager does not allow this (all the options I found are already available in this extension).

References, the cinnamon shadow implementation: https://github.com/linuxmint/muffin/blob/b3feb7f6933c443589c37c333885f2bdc1fd27c3/src/compositor/meta-shadow-factory.c

**Comment by BLuFeNiX** [comment]
@nathan818fr Thanks for the info!
