### ISSUE TITLE
Windows borders shadow

### ISSUE THREAD

**Issue by mlig212** [nathan818fr/cinnamon-user-shadows#3]
Hi Nathan,
With the new version of Mint (21, Vanessa) I have a issue with windows borders shadow. Because I thought it's a user-shadow issue I removed it from Spice Extension. The problem its stays on: a dark not blurred border appears) when I open a new window (Nemo, Firefox and all others). To make it disappear  I must move the window.
Is it a problem of some implementation User-Shadow rests in the Mint system core or only a new feature of the Mint Vanessa version?
Do you have an idea?
Thanks
Happy New Year
Regards
Marc
![userShadows](https://user-images.githubusercontent.com/22004799/210075429-2b6dbede-7e2e-4ca3-a525-0195dcda4fdd.jpg)

**Comment by nathan818fr** [comment]
Oh, sorry for the extremely late reply.

This extension only change parameters of the Cinnamon "shadow factory", unfortunately I don't know what can cause this, but the extension is not directly responsible indeed.
I hope this has been fixed since.
